name: financeplanner
description: A finance planner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  global_configuration: ^1.5.0

  stacked: ^1.6.1+1
  stacked_hooks:
  flutter_hooks:
  injectable:
  get_it:
  observable_ish:
  flare_flutter: ^2.0.4
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  http: ^0.12.1
  flutter_iconpicker: ^2.0.6
  flutter_typeahead: ^1.8.3
  flutter_web_auth: ^0.2.4
  flutter_secure_storage: ^3.3.3
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  injectable_generator:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - lang/en.json
    - lang/de.json
